"""initial

Revision ID: 24c89477f134
Revises: 
Create Date: 2023-07-08 13:19:19.502424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c89477f134'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.Text(), nullable=True),
                    sa.Column('last_name', sa.Text(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('email', sa.Text(), nullable=True),
                    sa.Column('msisdn', sa.Text(), nullable=True),
                    sa.Column('city', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
